part of views;

final infoArgsLookup = {
  '-cfg': S.current.args_cfg,
  '-ea': S.current.args_ea,
  '-eamaint': S.current.args_ea,
  '-w': S.current.args_w,
  '-c': S.current.args_c,
  '-s': S.current.args_s,
  '-k': S.current.args_k,
  '-stubs': S.current.args_stubs,
  '-io': S.current.args_io,
  '-acio': S.current.args_acio,
  '-icca': S.current.args_icca,
  '-device': S.current.args_device,
  '-extdev': S.current.args_extdev,
  '-sciunit': S.current.args_sciunit,
  '-sdvx': S.current.args_sdvx,
  '-iidx': S.current.args_iidx,
  '-iidxflipcams': S.current.args_iidxflipcams,
  '-jb': S.current.args_jb,
  '-rb': S.current.args_rb,
  '-pnm': S.current.args_pnm,
  '-mga': S.current.args_mga,
  '-gd': S.current.args_gd,
  '-nostalgia': S.current.args_nostalgia,
  '-bbc': S.current.args_bbc,
  '-2ch': S.current.args_2ch,
  '-ddr': S.current.args_ddr,
  '-ddrsd': S.current.args_ddrsd,
  '-o': S.current.args_o,
  '-qma': S.current.args_qma,
  '-sc': S.current.args_sc,
  '-network': S.current.args_network,
  '-subnet': S.current.args_subnet,
  '-netfixdisable': S.current.args_netfixdisable,
  '-acphookdisable': S.current.args_acphookdisable,
  '-signaldisable': S.current.args_signaldisable,
  '-createfiledebug': S.current.args_createfiledebug,
  '-pebprint': S.current.args_pebprint,
  '-bt5api': S.current.args_bt5api,
  '-printer': S.current.args_printer,
  '-printerpath': S.current.args_printerpath,
  '-printerformat': S.current.args_printerformat,
  '-printerjpgquality': S.current.args_printerjpgquality,
  '-printerclear': S.current.args_printerclear,
  '-urlslash': S.current.args_urlslash,
  '-disablenumpad': S.current.args_disablenumpad,
  '-disabletoprow': S.current.args_disabletoprow,
  '-realtime': S.current.args_realtime,
  '-sleep': S.current.args_sleep,
  '-h': S.current.args_h,
  '-a': S.current.args_a,
  '-v': S.current.args_v,
  '-e': S.current.args_e,
  '-y': S.current.args_y,
  '-p': S.current.args_p,
  '-r': S.current.args_r,
  '-url': S.current.args_url,
  '-modules': S.current.args_modules,
  '-scard': S.current.args_scard,
  '-scardflip': S.current.args_scardflip,
  '-scardtoggle': S.current.args_scardtoggle,
  '-reader': S.current.args_reader,
  '-togglereader': S.current.args_togglereader,
  '-cardio': S.current.args_cardio,
  '-cardioflip': S.current.args_cardioflip,
  '-sde': S.current.args_sde,
  '-api': S.current.args_api,
  '-apipass': S.current.args_apipass,
  '-apipretty': S.current.args_apipretty,
  '-apilogging': S.current.args_apilogging,
  '-apidebug': S.current.args_apidebug,
  '-dbghookdisable': S.current.args_dbghookdisable,
};

final info2PartArgsLookup = [
  '-k',
  '-network',
  '-subnet',
  '-printerpath',
  '-printerformat',
  '-printerjpgquality',
  '-urlslash',
  '-h',
  '-a',
  '-v',
  '-e',
  '-y',
  '-p',
  '-r',
  '-url',
  '-modules',
  '-reader',
  '-togglereader',
  '-sde',
  '-api',
  '-apipass',
  '-eamaint',
];

final playerCountMap = {
  "000": 2, // for debugging purposes
  "KFC": 1,
  "LDJ": 2,
  "J44": 1,
  "K44": 1,
  "L44": 1,
  "KDM": 1,
  "NBT": 1,
  "I36": 1,
  "MBR": 1,
  "M39": 1,
  "KGG": 1,
  "JGT": 1,
  "PIX": 1,
  "R66": 1, // actually has 4 players but only one reader
  "M32": 2, // guitars have 2 readers, drums only one
  "KDX": 2,
  "MDX": 2,
  "PAN": 1,
  "LMA": 1,
  "MMD": 1,
};

int getPlayerCount(String model) {
  return playerCountMap[model] ?? 2;
}
