name: spicecompanion
description: A fork of spicecompanion project
publish_to: none

version: 1.0.3+4

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  pool: ^1.4.0
  intl: ^0.17.0
  shared_preferences:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      path: packages/shared_preferences/shared_preferences
      ref: shared_preferences-v2.2.2-ohos-1.0.1
  flutter_nfc_reader:
    path: flutter-nfc-reader
  hex: ^0.1.2
  share_plus:
    git:
      url: https://gitcode.com/CPF-Flutter/flutter_plus_plugins.git
      path: packages/share_plus/share_plus
      ref: sensors_plus-7.2.0-ohos.1.0.0-beta.1
  path: ^1.8.0
  vibration: ^2.1.0
  mutex: ^1.1.0
  gallery_saver:
    git:
      url: https://gitcode.com/CPF-Flutter/fluttertpc_gallery_saver.git
      ref: 2.3.2-ohos-1.0.0
  window_manager: ^0.3.7
  url_launcher: 
    git:
      url: "https://gitcode.com/CPF-Flutter/flutter_packages.git"
      path: "packages/url_launcher/url_launcher"
      ref: url_launcher_v6.1.11-ohos-1.0.1
  extended_image: ^7.0.2
  wakelock_plus:
    git:
      url: https://gitcode.com/CPF-Flutter/fluttertpc_wakelock_plus.git
      path: wakelock_plus
      ref: 1.1.4-ohos.1.0.0-beta.1
  wakelock_plus_platform_interface: ^1.1.0

dependency_overrides:
  path_provider:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      path: packages/path_provider/path_provider
      ref: provider-v2.1.1-ohos-1.0.1

dev_dependencies: 
  flutter_lints: ^2.0.3
  #flutter_test:
  #  sdk: flutter

flutter:
  # bundle material icons
  uses-material-design: true
  assets:
    - assets/
    - assets/patches/

flutter_intl:
  enabled: true
