name: spicecompanion
description: A fork of spicecompanion project
publish_to: none

version: 1.0.1+2

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  pool: ^1.4.0
  intl: ^0.17.0
  shared_preferences:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      path: packages/shared_preferences/shared_preferences
      ref: shared_preferences-v2.2.2-ohos-1.0.1
  flutter_nfc_reader:
    path: flutter-nfc-reader
  hex: ^0.1.2
  share_plus:
    git:
      url: https://gitcode.com/CPF-Flutter/flutter_plus_plugins.git
      path: packages/share_plus/share_plus
      ref: sensors_plus-7.2.0-ohos.1.0.0-beta.1
  path: ^1.8.0
  #vibration: ^1.7.3
  mutex: ^1.1.0
  desktop_window: ^0.3.0
  gallery_saver:
    git:
      url: https://gitcode.com/CPF-Flutter/fluttertpc_gallery_saver.git
      ref: 2.3.2-ohos-1.0.0

dependency_overrides:
  path_provider:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      path: packages/path_provider/path_provider
      ref: provider-v2.1.1-ohos-1.0.1

dev_dependencies:
  #flutter_test:
  #  sdk: flutter

flutter:
  # bundle material icons
  uses-material-design: true
  assets:
    - assets/
    - assets/patches/

flutter_intl:
  enabled: true
